### ISSUE TITLE
Getting a 5-day forecast with Python 

### ISSUE THREAD

**Issue by pfonash** [raspberrypilearning/dress-for-the-weather#9] opened 2016-06-03 19:16 UTC
When I ran the following code: 

```
def get_weather_data(city_id):
    weather_data = get('http://api.openweathermap.org/data/2.5/forecast?id={}&APPID={}'.format(city_id, KEY))
    return weather_data.json()
```

I received a TypeError: 'dict' object not callable. I removed the parens after `json` and it worked.  Looks like one accesses the data returned by the get function through properties not functions?

**Comment by MarcScott** [comment] 2016-06-07 07:17
Hi @pfonash,
I can't reproduce this. With:

``` python
def get_weather_data(city_id):
    weather_data = get('http://api.openweathermap.org/data/2.5/forecast?id={}&APPID={}'.format(city_id, KEY))
    return weather_data.json()
```

When I then run:

``` python
get_weather_data(2643743)
```

for instance, I have the full json returned without errors.

**Comment by pfonash** [comment] 2016-06-13 19:49
Hi @MarcScott 

This is a picture of what I'm seeing.  Not sure if it's a Python version thing or a mistake in my code. 

![2016-06-13-154218_1776x952_scrot](https://cloud.githubusercontent.com/assets/6615343/16020971/4b955712-317e-11e6-8841-d92876951c0f.png)

**Comment by MarcScott** [comment] 2016-06-14 07:27
@pfonash Bizarre - I suppose it might be a python version problem. I ran this on 3.4.2 with no issues
![capture](https://cloud.githubusercontent.com/assets/4516338/16034428/b1903f4c-3209-11e6-8296-00162574b652.png)
Maybe @bennuttall has some idea what's going on.

**Comment by MarcScott** [comment] 2016-06-22 11:11
@pfonash Going to close this now. Please reopen if issue occurs when using latest version of Python 3

**Closed as completed** 2016-06-22 11:11 UTC
